### ISSUE TITLE
How to render math not in math tag?

### ISSUE THREAD

**Issue by rqy1458814497** [hexojs/hexo-math#124]
I use the commanded config and it only render math in tag.

I uncomment the `post.register` in main.js, and get several Error, seem like render math before render markdown will cause some problem.

So how to render `$...$` and `$$...$$`?

------

PS: I finally modify the post.js to: before post rendering, replace all `$...$` and `$$...$$` with math tags like this

```javascript
    value: function _render(match, math, isBlock) {
      var s = entities.decode(math);
      if (isBlock) s = '\n' + s + '\n';
      s = '{% math %} ' + s + '{% endmath %}';
      return s;
    }
```

but I don't know if there is some solution without modifying source code.

**Comment by mori-summer** [comment]
You can try ```npm install hexo-renderer-mathjax --save```

**Comment by curbengh** [comment]
This plugin has been rewritten and now math is embedded using a tag plugin:

```
{% mathjax %}
\frac{1}{x^2-1}
{% endmathjax %}
```

If you prefer to use `$...$` syntax, I recommend [the plugin](https://github.com/next-theme/hexo-filter-mathjax) as suggested by the previous comment.
