### ISSUE TITLE
ERROR Plugin load failed: hexo-math TypeError: Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by racheliurui** [hexojs/hexo-math#137]
Same code and same pipeline start to fail since 22Aug (21Aug no issue)
```
$ hexo cl
ERROR Plugin load failed: hexo-math
TypeError: Cannot read property 'register' of undefined
```

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/91517357-26f46e80-e920-11ea-8eb2-4570ef213fa0.png)
What is your hexo version?

**Comment by racheliurui** [comment]
Yes, that's the reason. Add the version definition. Thanks !
