### ISSUE TITLE
Something wrong with "\{\}"

### ISSUE THREAD

**Issue by sylxjtu** [hexojs/hexo-math#30]
`$\{\}$` seems doesn't work, it turns out nothing, is that bug related with this package?

**Comment by sylxjtu** [comment]
That's my code, the first formula can be displayed normally, but the second can't be displayed.
```
---
title: Math Test
date: 2016-07-23 20:58:56
tags:
---
$e^{\pi i} + 1 = 0$

$\{\}$
```

**Comment by stevenjoezhang** [comment]
Try
```
\\{\\}
```

**Comment by curbengh** [comment]
this plugin now uses tag plugin approach:

```
{% mathjax %}
e^{\pi i} + 1 = 0
{% endmathjax %}
```

If you prefer to use `$...$` syntax, I recommend [hexo-filter-mathjax](https://github.com/next-theme/hexo-filter-mathjax) developed by @stevenjoezhang .
