### ISSUE TITLE
Is there any config option with which I can select different engine(no/mathjax/katex) for each post?

### ISSUE THREAD

**Issue by WuChenxu** [hexojs/hexo-math#33]
title: xxx
categories: xx
tags: xx
comments: true
layout: post
date: 2016-07-12 01:03:42
math_engine: ------- is there something like this option in each post

**Comment by curbengh** [comment]
With the release of v4.0.0, it's now possible to select different engine:

```
{% katex %}
c = \pm\sqrt{a^2 + b^2}
{% endkatex %}
```

```
{% mathjax %}
\frac{1}{x^2-1}
{% endmathjax %}
```
