### ISSUE TITLE
Not compatible with yarn

### ISSUE THREAD

**Issue by w1ndy** [hexojs/hexo-math#38]
NPM is used in post-install script to install hexo-inject, which breaks packages installed by yarn. After installing hexo-math with yarn, hexo complains that local hexo could not be found despite that hexo folder exists in node_modules. However, removing node_modules and reinstalling hexo with NPM works.

**Comment by KayWu** [comment]
Similar problem.
When `yarn add hexo-math`, it succeeded. But when you call `hexo g`, there is an error.

> ERROR Local hexo not found in ~/blog
ERROR Try running: 'npm install hexo --save'

**Comment by stevenjoezhang** [comment]
`hexo-inject` is now deprecated. See https://github.com/hexojs/hexo-math/pull/130
