### ISSUE TITLE
为什么这个公式没法解析？

### ISSUE THREAD

**Issue by flystarhe** [hexojs/hexo-math#40]
$$H(y,\hat{y}) = - \frac{1}{n} \sum_n \sum_i y_{i,n} \log (\hat{y}_{i,n})$$

在其他工具和平台下都可以，就是hexo失败，请问是什么原因？

**Comment by gaussic** [comment]
似乎下标的大括号还不支持，这个问题仍然未修复

**Comment by lonelyWaiting** [comment]
在`_`前面加`\`转义就可以了

**Comment by JackieAnxis** [comment]
我也有这个问题，发了一个英文的issue了，期待能解决

**Comment by JackieAnxis** [comment]
@lonelyWaiting 但是这样子Markdown软件里面渲染就有问题了

**Comment by JackieAnxis** [comment]
I've found a solution in this article（in Chinese）
http://kubicode.me/2016/03/16/Hexo/Fix-Hexo-Bug-In-Mathjax/
the key idea is that, you can delete some part of regular expression the in marked.js(node_modules/marked/lib/marked.js)
image

**Comment by JackieAnxis** [comment]
I've found a solution in this article（in Chinese）
http://kubicode.me/2016/03/16/Hexo/Fix-Hexo-Bug-In-Mathjax/
the key idea is that, you can delete some part of regular expression the in marked.js(node_modules/marked/lib/marked.js)
see #48

**Comment by lonelyWaiting** [comment]
这个方案不治本,虽能解决多个`_`的情况,但多个`*`的情况一样无法解析.
个人感觉是`markdown`解析在`hexo-math`解析之前导致的.
不过不懂`javascript`,也仅是猜测罢了

**Comment by stevenjoezhang** [comment]
Try to escape `_` and `*` if you are using hexo-renderer-marked
