### ISSUE TITLE
install hexo-math failed

### ISSUE THREAD

**Issue by zhanglaplace** [hexojs/hexo-math#46]
Hi, i get an error when input this command 
npm install hexo-math --save

> hexo-math@3.0.4 postinstall E:\Documents\实验室\blog\hexo\blog\node_modules\hexo-math
> cd ../.. && npm install --save hexo-inject

npm WARN deprecated hexo-inject@1.0.0: The author does not use Hexo any more. This plugin is no longer maintained.

**Comment by NoahDragon** [comment]
Could you please paste the error log? I only saw a warning here.

**Comment by zhanglaplace** [comment]
@NoahDragon  i have solve the problem , Thanks all the same

**Comment by zhanglaplace** [comment]
@NoahDragon 为什么生成的博客，鼠标浏览时，会有蓝色的框。
![qq 20170908033300](https://user-images.githubusercontent.com/12178974/30181655-81c83f08-9446-11e7-925e-2b9bcc513ee6.png)

**Comment by NoahDragon** [comment]
@zhanglaplace 这可能是主题的样式造成的，可以尝试下更换主题试试。

**Comment by zhanglaplace** [comment]
@NoahDragon 嗯，多谢，才接触这个，所以问的问题比较low，多谢解答

**Comment by NoahDragon** [comment]
@zhanglaplace 不客气，先关闭此帖，有问题的话可以新开。

**Comment by HansenZhao** [comment]
请问是怎么解决的？我也遇到了同样的问题，别的地方都查不到解决方法

**Comment by amberframe** [comment]
请问是如何解决的？

**Comment by Vast-Stars** [comment]
同问

**Comment by icecoldless** [comment]
我不想换主题啊
