### ISSUE TITLE
The render equation is too small and is not centered when using math block

### ISSUE THREAD

**Issue by jdhao** [hexojs/hexo-math#47]
The math block works good but the generated LaTeX is small compared to the normal display equation, see below image for an example
![image](https://user-images.githubusercontent.com/16662357/31954328-e20a7eda-b917-11e7-8a2f-fa2b5ac78931.png)

So you can see that the equation is very small and not centered. It seems it is in inline mode. So how to use 
math block for display mode and make the output looks just like we are using the old form of display equation `$$some equation$$`.

**Comment by xandery-geek** [comment]
Hello, did you solve this issue? I would like to make the formula centered in math block as well. 
Could you share your solution?
