### ISSUE TITLE
Subscript can't be rendered if there are two or more '_{}' in my MathJax

### ISSUE THREAD

**Issue by JackieAnxis** [hexojs/hexo-math#48]
I have some problem in subscript rendering...
for example:
left is my MathJax, and the right is my render result

![image](https://user-images.githubusercontent.com/19246028/33167343-3bb911ae-d078-11e7-86aa-c875a0a65b29.png)

**Comment by JackieAnxis** [comment]
I've found a solution in this article（in Chinese）
http://kubicode.me/2016/03/16/Hexo/Fix-Hexo-Bug-In-Mathjax/
the key idea is that, you can delete some part of regular expression the in marked.js(node_modules/marked/lib/marked.js)
![image](https://user-images.githubusercontent.com/19246028/33169119-612fb9fa-d07e-11e7-8601-3d33af181583.png)

**Comment by stevenjoezhang** [comment]
Yes, you need to escape `_` to make it work:
```diff
-$l_{cv} l_{cv}$
+$l\_{cv} l\_{cv}$
```
