### ISSUE TITLE
Failed to render latex

### ISSUE THREAD

**Issue by liuslevis** [hexojs/hexo-math#49]
```
npm install hexo-cli -g
hexo init blog
cd blog
npm install
cd blog
npm install hexo-math --save
# add some latex to hello-world.md
hexo g
hexo s
```

package.json
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.4.4"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.4",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

**Comment by liwt31** [comment]
I met a similar problem. Though I gave up using hexo-math in the end, I tried to figure out what happened and that's what I do:
* Check if mathjax source url is correctly configured. The default one is down. See #41.
* Check if you have used something like $a+b=c$ to insert LaTeX. For me it doesn't work, but $$a+b=c$$ or \\(a+b=c\\) will do.

**Comment by stevenjoezhang** [comment]
This plugin is being remade. There is a discussion about it: https://github.com/hexojs/hexo-math/pull/130
I'm closing this issue. Please join the discussion there :)

**Comment by curbengh** [comment]
Hey everyone, I am rewriting hexo-math atm (https://github.com/hexojs/hexo-math/pull/130). It's ready for testing, just install it by `$ npm install hexo-math@curbengh/hexo-math#overhaul`. If there is no issue, I plan to release it on this weekend.
