### ISSUE TITLE
Failed to run $ npm install hexo-math --save

### ISSUE THREAD

**Issue by HuizhiXu** [hexojs/hexo-math#50]
Hello,

I met a error like this:
deprecated hexo-inject@1.0.0: The author does not use Hexo any more. This plugin is no longer maintained. 
It leads to incorrect display of my math form in website. Does anyone has the same problem?
By the way, my hexo version is 3.5.0. 

Best Wishes,
Huizhi

**Comment by belph** [comment]
I am having a similar issue. The postinstall script is giving me a warning about `hexo-inject` (that it's no longer maintained); it looks like `hexo-inject` isn't even on `npm`.

Why is this being installed via a `postinstall` script instead of via a dependency?

**Comment by fedidat** [comment]
+1

**Comment by stevenjoezhang** [comment]
`postinstall` script has been removed in https://github.com/hexojs/hexo-math/pull/71

Wait for https://github.com/hexojs/hexo-math/issues/101

**Comment by curbengh** [comment]
Hey everyone, I am rewriting hexo-math atm (https://github.com/hexojs/hexo-math/pull/130). It's ready for testing, just install it by `$ npm install hexo-math@curbengh/hexo-math#overhaul`. If there is no issue, I plan to release it on this weekend.
