### ISSUE TITLE
Inline mode cannot display

### ISSUE THREAD

**Issue by soulertsai** [hexojs/hexo-math#51]
In my case, if i use `$$...$$`, it works. But `$$...$$` not
How should I do to fix it?

**Comment by FranzSkuffka** [comment]
That's two identical things.

**Comment by MasKong** [comment]
You may use \\(formula\\).

**Comment by lishion** [comment]
@soulertsai I also have this problem. Do you find any solution?

**Comment by MasKong** [comment]
You may use \\(\\).
For example: \\(w_i \cdot x_i\\)

**Comment by MasKong** [comment]
You may use \\\(\\\).
For example: \\\(w_i \cdot x_i\\\)

**Comment by curbengh** [comment]
This plugin now uses tag plugin approach, so escaping shouldn't be necessary anymore.

```
{% mathjax %}
\frac{1}{x^2-1}
{% endmathjax %}
```

If you prefer to use `$...$` syntax, I recommend [hexo-filter-mathjax](https://github.com/next-theme/hexo-filter-mathjax).
