### ISSUE TITLE
case not works

### ISSUE THREAD

**Issue by MasKong** [hexojs/hexo-math#54]
\begin{cases}count(\cdot) &,\text{for the highest order}\\
continuationcount(\cdot) &,\text{for all other lower orders}
\end{cases}$$
Normally, it should be like the below image.
![image](https://user-images.githubusercontent.com/23203109/41958507-d5cf2bd6-7a1c-11e8-9f8b-7608eba62e01.png)
But in fact, it becoms the below image in my blog.
![image](https://user-images.githubusercontent.com/23203109/41958541-ee291ba6-7a1c-11e8-814c-d3bc4127eabc.png)
May I ask how to solve this problem?

**Comment by MakerGYT** [comment]
You should use double backslashes to wrap line
```sh
$$
\begin{cases}count(\cdot) &,\text{for the highest order}\\
continuationcount(\cdot) &,\text{for all other lower orders}
\end{cases}
$$
```
![image](https://user-images.githubusercontent.com/16568561/88493620-b1c21080-cfe4-11ea-8ea0-3340dc75405f.png)
=> [markdown-it-latex2img](https://github.com/MakerGYT/markdown-it-latex2img)，Stable server-side rendering solution

**Comment by curbengh** [comment]
Looks like mathjax itself does require double backslash (as mentioned by previous comment:

```
{% mathjax %}
\begin{cases}count(\cdot) &,\text{for the highest order}\\
continuationcount(\cdot) &,\text{for all other lower orders}
\end{cases}
{% endmathjax %}
```

![mathjax](https://user-images.githubusercontent.com/43627182/90841773-ad4b0680-e39c-11ea-9b07-7e26912fb125.png)
